"""empty message

Revision ID: a2d3f7f35b78
Revises: 56b9cab34f78
Create Date: 2023-04-22 11:50:14.177299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d3f7f35b78'
down_revision = '56b9cab34f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_time', sa.String(length=150), nullable=True))
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('appointment_time')

    # ### end Alembic commands ###
